### ISSUE TITLE
DigitalDisplayView will accept negative digits

### ISSUE THREAD

**Issue by steji113** [mattmemmesheimer/minesearch-reboot#3]
When binding to the Digits dependency property, a user of the DigitalDisplayView can specify a negative number of digits.

It is expected that a negative value should trigger the same validation that a zero value would.

**Comment by steji113** [comment]
Do you think this should have a view model so these particular cases can be tested better?

**Comment by mattmemmesheimer** [comment]
I originally had a view model, but opted to remove it to make the control more generic by exposing the value via a dependency property.  This way the data context of the control can be whatever the "client" wants instead of forcing them to use a specific view model.

The Digits property is an unsigned integer.  It is not a dependency property and not meant to be bound.

**Comment by steji113** [comment]
Derp this is what I get for quickly skimming over code in diffs. Makes perfect sense.
